# Part of the `rendler.eda` collection
# Author: Denis Rendler <connect[at]rendler.net>
# Copyright: 2025 Denis Rendler
# License: GPL-2.0-or-later
---

eda_ansible_packages:
  - ansible
  - ansible-runner
  - ansible-rulebook
  - pytz
