---

- name: Run the configuration sequence for roles
  hosts: all

  tasks:
    - name: Load the roles to run
      run_once: true
      tags: always
      ansible.builtin.set_fact:
        roles_list: '{{ lookup("env", "ROLES").split(",") }}'

    - name: List roles to be executed
      tags: always
      ansible.builtin.debug:
        var: roles_list

    - name: Running role(s)
      tags: always
      ansible.builtin.include_role:
        name: '{{ role }}'
        tasks_from: configure.yaml
      loop: "{{ roles_list }}"
      loop_control:
        loop_var: role
