---

- name: Update all installed packages using APT module
  ansible.builtin.apt:
    name: '*'
    state: latest
    update_cache: true
    only_upgrade: true
  register: apt_update_status

- name: Remove packages not needed anymore
  ansible.builtin.apt:
    autoremove: true

- name: Reboot when packages were updated # noqa: no-handler
  ansible.builtin.reboot:
    post_reboot_delay: 60
  when: apt_update_status.changed
