---

- name: Update all installed packages using YUM module
  ansible.builtin.dnf:
    name: '*'
    state: latest
    update_cache: true
    update_only: true
  register: yum_update_status

- name: Remove packates not needed anymore # noqa: no-handler
  ansible.builtin.dnf:
    autoremove: true

- name: Reboot when packages were updated # noqa: no-handler
  ansible.builtin.reboot:
  when: yum_update_status.changed
